name: MinersShaft
version: ${project.version}
main: me.imdanix.mine.MinersShaft
api-version: '1.13'
authors: [imDaniX]
description: Just for some regenerative mines
depend: [WorldGuard]
commands:
  minersshaft:
    aliases: [shaft]
    permission: minersshaft.reload
